version: '3.8'
services:

  next:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    volumes:
      - ./.env.local:/app/.env.local

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freelancrm
